[keyboard]
keymap_layout=fr
numlock-on=true

[launcher]
icon=/usr/share/icons/Mint-X/apps/24/terminal.png
path=/usr/bin/weston-terminal

[launcher]
; icon=~/.local/share/waydroid/data/icons/org.phramusca.jamuz.png
icon=~/Bureau/Waydroid/org.phramusca.jamuz.png
path=/usr/bin/waydroid app launch org.phramusca.jamuz
